clubs/urls.py
from django.urls import path
from . import views

app_name = 'clubs'

urlpatterns = [
    path('', views.ClubList.as_view(), name='index'),
    path('club/<int:pk>/', views.ClubView.as_view(), name='club'),
    path('club/<int:club_pk>/news_list/', views.ClubNewsListView.as_view(), name='club_list_news'),
    path('club/<int:club_pk>/news/<int:pk>/', views.ClubNewsDetailView.as_view(), name='club_news'),
    path('club/<int:pk>/players/', views.ClubPlayersList.as_view(), name='club_players'),
    path('create/', views.ClubCreationView.as_view(), name='create_club'),
    path('edit_club/<int:pk>/', views.UpdateClubView.as_view(), name='edit_club'),
    path('my_clubs/', views.MyClubList.as_view(), name='my_clubs'),
    path('participation_in_clubs/', views.ParticipationClubList.as_view(), name='participation_in_clubs'),
    path('add_potential_members/<int:club_pk>/', views.add_player_to_potential_club_members, name='add_potential_members'),
    path('potential_members/<int:club_pk>/', views.potential_members, name='potential_members'),
    path('add_to_open_club_members/<int:club_pk>/', views.add_to_open_club_members, name='add_to_open_club_members'),
    path('to_real_members/<int:club_pk>/<int:player_pk>/', views.add_potential_club_member_to_real_members, name='to_real_members'),
    path('reject_potential_member/<int:club_pk>/<int:player_pk>/', views.reject_potential_member, name='reject_potential_member'),
    path('potential_club_news_list/<int:club_pk>/', views.potential_club_news_list, name='potential_club_news_list'),
    path('potential_club_news/<int:club_pk>/<int:pk>/', views.PotentialClubNewsDetailView.as_view(), name='potential_club_news'),
    path('to_club_news/<int:club_pk>/<int:news_pk>/', views.add_potential_club_news, name='to_club_news'),
    path('reject_club_news/<int:club_pk>/<int:news_pk>/', views.reject_potential_club_news, name='reject_club_news'),
]

news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.get_news_index_page, name='index'),
    path('rules', views.get_rules, name='rules'),
    path('about_us', views.about_us, name='about_us'),
    path('news', views.PublicNewsListView.as_view(), name='public_news_list'),
    path('news/<int:pk>/', views.PublicNewsDetailView.as_view(), name='get_the_open_news'),
    path('creating_news/', views.NewsCreationView.as_view(), name='creating_news'),
    path('updating_news/<int:pk>/', views.UpdateNewsView.as_view(), name='updating_news'),
    path('like_news/<int:news_pk>/', views.like_news, name='like_news'),
]

players/urls.py
from django.urls import path
from . import views

app_name = 'players'

urlpatterns = [
    path('', views.get_players_index_page, name='index'),
    path('player_info/<slug:username>/', views.get_player_info, name='player_info'),
    path('plot_rating_data/<slug:username>/', views.plot_rating_graph, name='plot_rating_data'),
    # path('change_rating/', views.change_rating, name='change_rating'),
    path('registration/', views.register_view, name='registration'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile, name='profile'),

    path('notifications/', views.AllNotificationListView.as_view(), name='notifications'),
    path('notifications/invitation/', views.InvitationNotificationListView.as_view(), name='invitation_notifications'),
    path('notifications/events/', views.EventNotificationListView.as_view(), name='event_notifications'),
    path('notifications/clubs/', views.ClubNotificationListView.as_view(), name='clubs_notifications'),
    path('notifications/news/', views.NewsNotificationListView.as_view(), name='news_notifications'),
    path('notifications/actions/', views.NotificationActions.as_view(), name='notifications_actions'),

    path('validate_email/', views.validate_email, name='validate_email'),
    path('validate_username/', views.validate_username, name='validate_username'),
    path('validate_password_view/', views.validate_password_view, name='validate_password_view'),

    # path('api/v1/players_list/', views.PlayersInfoAPIView.as_view(), name='api_players_list'),
    path('api/v1/api_players_rating/', views.PlayersRatingAPIView.as_view(), name='api_players_rating'),
]

ttennis/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar
import notifications.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('', include('news.urls', namespace='news')),
    path('players/', include('players.urls', namespace='players')),
    path('events/', include('events.urls', namespace='events')),
    path('games/', include('games.urls', namespace='games')),
    path('clubs/', include('clubs.urls', namespace='clubs')),
    path('additions/', include('additions.urls', namespace='additions')),
    path('tournaments/', include('tournaments.urls', namespace='tournaments')),
]


# For debug_toolbar
if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls))
    ]

# For media files
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clubs/models.py
from django.db import models
from django.utils import timezone


class Club(models.Model):
    """The model has info about each club"""

    class OPEN(models.IntegerChoices):
        YES = 1, 'открытый'
        NO = 0, 'закрытый'

    name = models.CharField(max_length=255, verbose_name='Имя клуба', unique=True)
    owner = models.ForeignKey('players.Player', on_delete=models.CASCADE, related_name='club_owner',
                              verbose_name='Владелец клуба', null=True, blank=True)
    is_open = models.SmallIntegerField(default=OPEN.YES, choices=OPEN.choices, verbose_name='Статус')
    city = models.ForeignKey('additions.City', on_delete=models.CASCADE, related_name='club_city', verbose_name='Город')
    addr = models.CharField(max_length=255, verbose_name='Адрес')
    description = models.TextField(null=True, blank=True, verbose_name='Описание')
    website = models.CharField(max_length=2500, null=True, blank=True, verbose_name='Сайт')
    logo = models.ImageField(upload_to='clubs_logo', null=True, blank=True, verbose_name='Логотип')
    telegram = models.CharField(max_length=255, null=True, blank=True, verbose_name='Телеграмм')
    members = models.ManyToManyField('players.Player', related_name='club_members', verbose_name='Участники клуба')
    potential_members = models.ManyToManyField('players.Player', blank=True, related_name='potential_club_members',
                                               verbose_name='Потенциальные участники клуба')
    games = models.ManyToManyField('games.Game', blank=True, related_name='club_game', verbose_name='Игры')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания записи')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения записи')

    class Meta:
        verbose_name_plural = 'Клубы'
        verbose_name = 'Клуб'

    def __str__(self):
        return f'{self.name}'


class ClubReview(models.Model):
    """The model exists for reviews about the club"""

    club = models.ForeignKey(Club, on_delete=models.CASCADE, related_name='clubreview_club',
                             verbose_name='Заголовок отзыва')
    text = models.TextField(verbose_name='Текст отзыва')
    player = models.ForeignKey('players.Player', on_delete=models.CASCADE, related_name='clubreview_player')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания записи')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения записи')

    class Meta:
        verbose_name_plural = 'Отзывы'
        verbose_name = 'Отзыв'

    def __str__(self):
        return f'Отзыв о клубе {self.club} от пользователя {self.player}'

clubs/forms.py
from django import forms
from django.core.validators import MinValueValidator

from .models import Club
from additions.models import City


class ClubCreationForm(forms.ModelForm):
    name = forms.CharField(label='Название клуба', widget=forms.TextInput(attrs={'class': 'm-1'}))
    is_open = forms.ChoiceField(label='Открытый/закрытый', choices=Club.OPEN.choices,
                                widget=forms.Select(attrs={'class': 'm-1'}))
    city = forms.ModelChoiceField(label='Город', queryset=City.objects.all(),
                                  widget=forms.Select(attrs={'class': 'm-1'}))
    addr = forms.CharField(label='Адрес', required=False, widget=forms.TextInput(attrs={'class': 'm-1'}))
    description = forms.CharField(label='Описание', required=False, widget=forms.Textarea(attrs={'class': 'm-1'}))
    website = forms.CharField(label='Веб-сайт', required=False, widget=forms.TextInput(attrs={'class': 'm-1'}))
    logo = forms.ImageField(label='Логотип', required=False, widget=forms.FileInput(attrs={'class': 'm-1'}))
    telegram = forms.CharField(label='Telegram', required=False, widget=forms.TextInput(attrs={'class': 'm-1'}))

    class Meta:
        model = Club
        fields = ['name', 'is_open', 'city', 'addr', 'description',
                  'website', 'logo', 'telegram']


class ClubsFilterForm(forms.Form):
    name = forms.CharField(label='Название', required=False, widget=forms.TextInput(attrs={'class': 'm-1'}))
    is_open = forms.ChoiceField(label='Статус', required=False, choices=[('', 'Любой')] + list(Club.OPEN.choices),
                                widget=forms.Select(attrs={'class': 'm-1'}))
    city = forms.ModelChoiceField(label='Город', required=False, queryset=City.objects.all(),
                                  empty_label='Укажите город', widget=forms.Select(attrs={'class': 'm-1'}))
    min_participants = forms.IntegerField(
        label='Минимум участников',
        required=False,
        widget=forms.NumberInput(attrs={'class': 'm-1', 'style': 'width: 65px; display: flex; align-items: center;'}),
        validators=[MinValueValidator(1, message='Участников клуба не может быть менее одного.')]
    )
    max_participants = forms.IntegerField(
        label='Максимум участников',
        required=False,
        widget=forms.NumberInput(attrs={'class': 'm-1', 'style': 'width: 65px; display: flex; align-items: center;'}),
        validators=[MinValueValidator(1, message='Участников клуба не может быть менее одного.')]
    )
    has_logo = forms.BooleanField(label='С логотипом', required=False, initial=False,
                                  widget=forms.CheckboxInput(attrs={'class': 'm-1'}))


    class Meta:
        model = Club
        fields = ['name', 'min_participants', 'max_participants', 'city', 'is_open', 'has_logo']

templates/clubs/club.html
{% extends 'clubs/club_template.html' %}
{% load static %}

{% block club_page_content %}
    <div class="main-container">
        {% include "clubs/club_card.html" %}
    </div>
{% endblock club_page_content %}

templates/clubs/club_card.html
<div class="card mb-3">
    <div class="card-body d-flex align-items-center">
        <div>
            <h5 class="card-title">{{ club.name }}</h5>
            <p class="card-text">{{ club.description }}</p>
            <p class="card-text"><strong>Участников:</strong> {{ club.members.count }}</p>
            <p class="card-text"><strong>Местоположение:</strong>
                <br>
                {% if club.city %}г. {{ club.city }}{% endif %},
                {% if club.addr %}
                    {{ club.addr }}
                {% endif %}
            </p>
            <p class="card-text"><strong>Рейтинг среди игроков:</strong> 4.7 / 5</p>
            <p class="card-text"><strong>Статус: </strong>{{ club.get_is_open_display }}</p>
            {% if not club_page %}
                {% if club.owner == request.user %}
                    <p><i>Это мой клуб</i></p>
                    <a href="{% url 'clubs:club' club.pk %}" class="btn btn-primary">Войти</a>
                    <a href="{% url 'clubs:edit_club' club.pk %}" class="btn btn-warning">Редактировать</a>
                {% elif request.user in club.members.all %}
                    <p><i>Вы состоите в этом клубе</i></p>
                    <a href="{% url 'clubs:club' club.pk %}" class="btn btn-primary">Войти</a>
                {% elif user.is_authenticated and club.is_open %}
                    <p><i>Вы можете ознакомиться с клубом подробнее и вступить в него прямо сейчас.</i></p>
                    <a href="{% url 'clubs:club' club.pk %}" class="btn btn-info text-white">Ознакомиться</a>
                {% elif user.is_authenticated and request.user in club.potential_members.all %}
                    <p><i>Вы уже подали заявку на вступление в этот закрытый клуб. Ожидайте её рассмотрения владельцем клуба.</i></p>
                {% elif user.is_authenticated and not club.is_open %}
                    {% include 'clubs/add_to_potential_members.html' %}
                    <p><i id="will-change-{{ club.pk }}">Доступ в клуб ограничен. Чтобы открыть страницу клуба вы должны быть его членом.</i></p>
                    <a href="#" class="btn btn-secondary add-to-potential-members" id="to-remove-{{ club.pk }}" data-club-pk="{{ club.pk }}">Подать заявку</a>
                {% elif club.is_open %}
                    <p><i>Вы можете ознакомиться с клубом подробнее и вступить в него прямо сейчас.
                        Для этого необходимо сначала <a href="{% url 'players:login' %}">войти</a> на сайт.</i></p>
                {% else %}
                    <p><i>Доступ в клуб ограничен. Чтобы открыть страницу клуба вы должны быть его членом.
                    Для этого необходимо сначала <a href="{% url 'players:login' %}">войти</a> на сайт, а затем подать заявку на вступление.</i></p>
                {% endif %}
            {% endif %}
        </div>
        <div class="ml-auto px-5">
            {% if club.logo %}
                <img src="{{ club.logo.url }}" width="150px">
            {% endif %}
        </div>
    </div>
</div>

templates/clubs/club_menu.html
<div class="container m-1 p-1 border-bottom">
    <div class="btn-group me-2" role="group" aria-label="First group">
        <a href="{% url 'clubs:club_list_news' club_pk=club.pk %}"><button type="button" class="btn btn-light text-uppercase">Новости</button></a>
        <a href="{% url 'clubs:club_players' club.pk %}"><button type="button" class="btn btn-light text-uppercase">Участники</button></a>
        <a href="{% url 'clubs:create_club' %}"><button type="button" class="btn btn-light text-uppercase">Игры</button></a>
        <a href="{% url 'clubs:participation_in_clubs' %}"><button type="button" class="btn btn-light text-uppercase">Галерея</button></a>
        <a href="{% url 'clubs:participation_in_clubs' %}"><button type="button" class="btn btn-light text-uppercase">Отзывы</button></a>
        <a href="{% url 'clubs:club' club.pk %}"><button type="button" class="btn btn-light text-uppercase">О_клубе</button></a>
        {% if request.user in club.members.all %}
            {% if request.user != club.owner %}
                <a href="{% url 'news:creating_news' %}"><button type="button" class="btn btn-light text-uppercase">Предложить_новость</button></a>
            {% else %}
                <div class="dropdown">
                  <a class="btn btn-warning dropdown-toggle text-uppercase" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                    Управление клубом
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                      <li><a class="dropdown-item" href="{% url 'clubs:edit_club' club.pk %}">Изменить карточку клуба</a></li>
                      <li><a class="dropdown-item" href="{% url 'news:creating_news' %}">Опубликовать новость</a></li>
                      <li><a class="dropdown-item" href="{% url 'clubs:potential_club_news_list' club_pk=club.pk %}">Предложенные новости</a></li>
                    {% if not club.is_open %}
                        <li><a class="dropdown-item" href="{% url 'clubs:potential_members' club_pk=club.pk %}">Потенциальные участники</a></li>
                    {% endif %}
                  </ul>
                </div>
            {% endif %}
        {% endif %}
        {% if user not in club.members.all %}
            <a href="{% url 'clubs:add_to_open_club_members' club_pk=club.pk %}" class="btn btn-primary text-uppercase mx-1">Вступить</a>
        {% endif %}
    </div>
</div>

templates/clubs/club_news_detail.html
{% extends 'clubs/club_template.html' %}
{% load static %}

{% block javascripts %}
  {% include 'news/news_like.html' %}
{% endblock %}

{% block club_page_content %}
  {% if news %}
    <div class="container mt-2">
      <div class="card mb-4">
        {% if news.cover %}
          <img src="{{ news.cover.url }}" class="card-img-top" alt="{{ news.name }}" style="max-height: 400px; object-fit: cover;">
        {% endif %}
        <div class="card-body">
          <h3 class="card-title">{{ news.name }}</h3>
          <p class="card-text">
            <small class="text-muted">{{ news.date_time }}</small>
            <small class="text-muted">Автор: <a href="{% url 'players:player_info' username=news.author.username %}">{{ news.author.username }}</a></small>
            {% if news.club %}
              {% if news.club.is_open or request.user in news.club.members.all %}
                <small class="text-muted">Опубликовано от имени клуба "<a href="{% url 'clubs:club' news.club.pk %}">{{ news.club.name }}"</a>.</small>
              {% else %}
                <small class="text-muted">Опубликовано от имени клуба "{{ news.club.name }}"</small>
              {% endif %}
            {% endif %}
          </p>
          <p class="card-text">{{ news.content }}</p>
          <div class="d-flex justify-content-between align-items-center">
            <div class="d-flex">
              {% if user.is_authenticated %}
                {% if news.liker %}
                  <img src="{% static 'img/like_pressed.svg' %}" class="news_like_view_change me-2" width="20px" data-news-pk="{{ news.pk }}">
                {% else %}
                  <img src="{% static 'img/like_unpressed.svg' %}" class="news_like_view_change me-2" width="20px" data-news-pk="{{ news.pk }}">
                {% endif %}
              {% else %}
                <img src="{% static 'img/like_unpressed.svg' %}" class="me-2" width="20px">
              {% endif %}
              <span class="text-muted" id="news_{{ news.pk }}_like_count">{{ news.newslike_news.count }}</span>
              <small class="text-muted ms-2">Просмотры: {{ news.views_count }}</small>
              <small class="text-muted ms-2">Комментарии: {{ news.newscomment_news.count }}</small>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="container">
      <h4 class="mt-4 mb-3">Комментарии</h4>
      {% if page_obj %}
        {% for comment in page_obj %}
          <div class="card mb-2">
            <div class="card-body">
              <p class="card-text">
                <small class="text-muted">Автор: <a href="{% url 'players:player_info' username=comment.commenter.username %}">{{ comment.commenter.username }}</a></small>
                <small class="text-muted">{{ comment.created_at }}</small>
              </p>
              <p>{{ comment.comment }}</p>
            </div>
          </div>
        {% endfor %}
      {% else %}
        <p class="text-muted">Пока нет комментариев.</p>
      {% endif %}
      {% include 'paginator.html' %}
      {% if user.is_authenticated %}
        <h4 class="mt-4 mb-3">Добавить комментарий</h4>
        <form method="post">
          {% csrf_token %}
          <div class="mb-3">
            {{ form.comment }}
            {% if form.comment.errors %}
              <div class="text-danger">{{ form.comment.errors }}</div>
            {% endif %}
          </div>
          <button type="submit" class="btn btn-primary">Отправить</button>
        </form>
      {% else %}
        <p class="mt-4 mb-3">Чтобы оставить комментарий, <a href="{% url 'players:login' %}">войдите</a> под своей учётной записью.</p>
      {% endif %}
    </div>
  {% endif %}
{% endblock %}

templates/clubs/club_potential_members.html
{% extends 'clubs/club_template.html' %}
{% load static %}

{% block club_page_content %}
<div class="main-container">
    <table class="registration-form">
        <thead>
          <tr>
            {% if players %}
                <th><h4>Заявки на вступление в клуб</h4></th>
            {% else %}
                <th><h4>На данный момент заявок на вступление в клуб нет</h4></th>
            {% endif %}
          </tr>
        </thead>
        <tbody>
        {% for player in players %}
          <tr id="to-remove-{{ player.pk }}">
            <td>
              <a href="{% url 'players:player_info' username=player.username %}">{{ player.username }}</a> — {{ player.first_name }} {{ player.last_name }}
            </td>
            <td>
              <a href="#" class="btn btn-primary m-1 approve" data-player-pk="{{ player.pk }}" data-club-pk="{{ club.pk }}">Одобрить</a>
            </td>
            <td>
              <a href="#" class="btn btn-secondary m-1 reject" data-player-pk="{{ player.pk }}" data-club-pk="{{ club.pk }}">Отклонить</a>
            </td>
          </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% include 'clubs/approve_or_reject_potential_member.html' %}
{% endblock %}

templates/clubs/club_potential_news.html
{% extends 'clubs/club_template.html' %}
{% load static %}

{% block club_page_content %}
<div class="main-container">
    <table class="registration-form">
        <thead>
          <tr>
            {% if news %}
                <th><h4>Новости</h4></th>
            {% else %}
                <th><h4>На данный момент предложенных новостей нет</h4></th>
            {% endif %}
          </tr>
        </thead>
        <tbody>
        {% for item in news %}
          <tr id="to-remove-{{ item.pk }}">
            <td>
                <h5>{{ item.name }}</h5>
            </td>
              <td>
                  <a class="mx-5" href="{% url 'clubs:potential_club_news' club_pk=club.pk pk=item.pk %}">Читать</a>
              </td>
            <td>
              <a href="#" class="btn btn-primary m-1 approve" data-news-pk="{{ item.pk }}" data-club-pk="{{ club.pk }}">Принять</a>
            </td>
            <td>
              <a href="#" class="btn btn-secondary m-1 reject" data-news-pk="{{ item.pk }}" data-club-pk="{{ club.pk }}">Отклонить</a>
            </td>
          </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% include 'clubs/approve_or_reject_potential_news.html' %}
{% endblock %}

templates/clubs/club_template.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ title }}{% endblock %}
{% block content %}

<!-- Дополнительные стили -->
<link rel="stylesheet" href="{% static 'css/clubs.css' %}">

{% if club.is_open or user in club.members.all %}
    {% include "clubs/club_menu.html"  %}
    <!-- Основной контент страницы -->
<div class="container">

    {% block club_page_content %}
    {% endblock %}

</div>

{% else %}
    {% if user.is_authenticated %}
        <p><i>Доступ в клуб ограничен. Чтобы открыть страницу клуба вы должны быть его членом.
        <a href="{% url 'clubs:add_potential_members' pk=club.pk %}" class="">Подать заявку</a> на вступление.</i></p>
    {% else %}
        <p><i>Доступ в клуб ограничен. Чтобы открыть страницу клуба вы должны быть его членом.
        Для этого необходимо сначала <a href="{% url 'players:login' %}">войти</a> на сайт, а затем подать заявку на вступление.</i></p>
    {% endif %}
{% endif %}

{% endblock content %}

templates/clubs/clubs_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ title }}{% endblock %}
{% block content %}

<div class="my-2 row">
    <div class="col-8 col-md-4">
        <h2>Выбрать клубы</h2>
        {% if player_participant_in_club %}
            <form method="get" action="{% url 'clubs:participation_in_clubs' %}">
        {% elif players_clubs %}
            <form method="get" action="{% url 'clubs:my_clubs' %}">
        {% else %}
            <form method="get" action="{% url 'clubs:index' %}">
        {% endif %}
            <table class="registration-form">
                <tr>
                    <div style="display: flex; align-items: center;">
                        <label for="{{ filter_form.name.id_for_label }}">Название:</label>
                         {{ filter_form.name }}
                    </div>
                </tr>

                <tr>
                    <div style="display: flex; align-items: center;">
                        <label for="{{ filter_form.min_participants.id_for_label }}">Участников от</label>
                         {{ filter_form.min_participants }}
                        <label for="{{ form.max_participants.id_for_label }}">до</label>
                        {{ filter_form.max_participants }}
                    </div>
                </tr>

                <tr>
                    <td>
                        <label for="{{ filter_form.has_logo.id_for_label }}">Логотип:</label>
                    </td>
                    <td valign="top">
                        {{ filter_form.has_logo }}
                    </td>
                </tr>

                <tr>
                    <td>
                        <label for="{{ filter_form.is_open.id_for_label }}">Статус:</label>
                    </td>
                    <td valign="top">
                        {{ filter_form.is_open }}
                    </td>
                </tr>

                <tr>
                    <td>
                        <label for="{{ filter_form.city.id_for_label }}">Город:</label>
                    </td>
                    <td valign="top">
                        {{ filter_form.city }}
                    </td>
                </tr>
            </table>

            <div class="my-2" style="background-color: rgba(255, 0, 0, 0.1);">
                {{ filter_form.name.errors }}
                {{ filter_form.min_participants.errors }}
                {{ filter_form.max_participants.errors }}
                {{ filter_form.has_logo.errors }}
                {{ filter_form.is_open.errors }}
                {{ filter_form.city.errors }}
            </div>

            <button type="submit" class="btn btn-secondary">Применить фильтры</button>
        </form>
    </div>

    <div class="col-12 col-md-8 my-2">
        {% if clubs %}
            <h6>Всего клубов: {{ clubs_count }}</h6>
            {% for club in clubs %}
                <div class="mb-4">
                    {% include "clubs/club_card.html"  %}
                </div>
            {% endfor %}
        {% else %}
            <p>Во Вашему запросу не найдено ни одного клуба.</p>
        {% endif %}
    </div>
</div>

{% include "paginator_with_filter.html"  %}

{% endblock content %}

templates/clubs/create_club.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ title }}{% endblock %}
{% block content %}

<h2>{{ title }}</h2>
<div class="mb-4 col-12 col-md-6 col-lg-4">
    <form method="POST" action="{% url 'clubs:create_club' %}" enctype="multipart/form-data">
       {% csrf_token %}
       <table class="registration-form">
        <tr>
            <td>
                <label for="{{ form.name.id_for_label }}">Имя</label>
            </td>
            <td valign="top">
                {{ form.name }}
            </td>
        </tr>

        <tr>
            <td>
                <label for="{{ form.is_open.id_for_label }}">Статус</label>
            </td>
            <td valign="top">
                {{ form.is_open }}
            </td>
        </tr>

        <tr>
            <td>
                <label for="{{ form.city.id_for_label }}">Город</label>
            </td>
            <td valign="top">
                {{ form.city }}
            </td>
        </tr>

        <tr>
            <td>
                <label for="{{ form.addr.id_for_label }}">Адрес</label>
            </td>
            <td valign="top">
                {{ form.addr }}
            </td>
        </tr>

        <tr>
            <td class="align-top">
                <label for="{{ form.description.id_for_label }}">Описание</label>
            </td>
            <td valign="top">
                {{ form.description }}
            </td>
        </tr>

        <tr>
            <td>
                <label for="{{ form.website.id_for_label }}">Сайт</label>
            </td>
            <td valign="top">
                {{ form.website }}
            </td>
        </tr>

        <tr>
            <td>
                <label for="{{ form.telegram.id_for_label }}">Telegram</label>
            </td>
            <td valign="top">
                {{ form.telegram }}
            </td>
        </tr>

        <tr>
            <td>
                <label for="{{ form.logo.id_for_label }}">Логотип</label>
            </td>
            <td>
                {{ form.logo }}
            </td>
        </tr>
    </table>

        <div class="my-2" style="background-color: rgba(255, 0, 0, 0.1);">
            {{ form.name.errors }}
            {{ form.is_open.errors }}
            {{ form.city.errors }}
            {{ form.addr.errors }}
            {{ form.description.errors }}
            {{ form.website.errors }}
            {{ form.logo.errors }}
            {{ form.telegram.errors }}
        </div>

        <button type="submit" class="btn btn-primary text-uppercase">Создать клуб</button>
    </form>
</div>


{% endblock content %}