events/urls.py
from django.urls import path
from . import views

app_name = 'events'

urlpatterns = [
    path('', views.EventListView.as_view(), name='events'),
    path('my_events/', views.MyEventListView.as_view(), name='my_events'),
    path('event/<int:event_pk>/', views.show_event, name='event'),
    path('join_the_club/<int:event_pk>/', views.join_the_club, name='join_the_club'),
    path('search_partner/', views.get_search_partner_page, name='search_partner'),
    path('create_event/', views.EventCreationView.as_view(), name='create_event'),
    path('update_event/<int:pk>/', views.update_event, name='update_event'),
    path('invite_to_play/<int:player_pk>/', views.invite_to_play, name='invite_to_play'),
    path('reject_invitation/<int:invitation_pk>/<int:player_pk>/', views.reject_invitation, name='reject_invitation'),
    path('accept_invitation/<int:invitation_pk>/', views.accept_invitation, name='accept_invitation'),

    ]

news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.get_news_index_page, name='index'),
    path('rules', views.get_rules, name='rules'),
    path('about_us', views.about_us, name='about_us'),
    path('news', views.PublicNewsListView.as_view(), name='public_news_list'),
    path('news/<int:pk>/', views.PublicNewsDetailView.as_view(), name='get_the_open_news'),
    path('creating_news/', views.NewsCreationView.as_view(), name='creating_news'),
    path('updating_news/<int:pk>/', views.UpdateNewsView.as_view(), name='updating_news'),
    path('like_news/<int:news_pk>/', views.like_news, name='like_news'),
]

players/urls.py
from django.urls import path
from . import views

app_name = 'players'

urlpatterns = [
    path('', views.get_players_index_page, name='index'),
    path('player_info/<slug:username>/', views.get_player_info, name='player_info'),
    path('plot_rating_data/<slug:username>/', views.plot_rating_graph, name='plot_rating_data'),
    # path('change_rating/', views.change_rating, name='change_rating'),
    path('registration/', views.register_view, name='registration'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile, name='profile'),

    path('notifications/', views.AllNotificationListView.as_view(), name='notifications'),
    path('notifications/invitation/', views.InvitationNotificationListView.as_view(), name='invitation_notifications'),
    path('notifications/events/', views.EventNotificationListView.as_view(), name='event_notifications'),
    path('notifications/clubs/', views.ClubNotificationListView.as_view(), name='clubs_notifications'),
    path('notifications/news/', views.NewsNotificationListView.as_view(), name='news_notifications'),
    path('notifications/actions/', views.NotificationActions.as_view(), name='notifications_actions'),

    path('validate_email/', views.validate_email, name='validate_email'),
    path('validate_username/', views.validate_username, name='validate_username'),
    path('validate_password_view/', views.validate_password_view, name='validate_password_view'),

    # path('api/v1/players_list/', views.PlayersInfoAPIView.as_view(), name='api_players_list'),
    path('api/v1/api_players_rating/', views.PlayersRatingAPIView.as_view(), name='api_players_rating'),
]

ttennis/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar
import notifications.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('', include('news.urls', namespace='news')),
    path('players/', include('players.urls', namespace='players')),
    path('events/', include('events.urls', namespace='events')),
    path('games/', include('games.urls', namespace='games')),
    path('clubs/', include('clubs.urls', namespace='clubs')),
    path('additions/', include('additions.urls', namespace='additions')),
    path('tournaments/', include('tournaments.urls', namespace='tournaments')),
]


# For debug_toolbar
if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls))
    ]

# For media files
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

players/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator
from django.urls import reverse
from django.utils import timezone


class Player(AbstractUser):
    """Model has info about user that is player in the project"""

    class SEX(models.IntegerChoices):
        MALE = 1, 'мужской'
        FEMALE = 0, 'женский'

    class HAND(models.IntegerChoices):
        RIGHT = 1, 'правая'
        LEFT = 0, 'левая'

    class SEARCHABLE(models.IntegerChoices):
        YES = 1, 'правая'
        NO = 0, 'левая'

    class STYLE(models.TextChoices):
        ATTACKING = 'attacking', 'атакующий'
        DEFENSIVE = 'defensive', 'защитный'
        MIXED = 'mixed', 'смешанный'
        MASCULINE = 'masculine', 'мужской'
        FEMININE = 'feminine', 'женский'
        SEXLESS = 'sexless', 'бесполый'
        CLUMSY = 'clumsy', 'корявый'
        UGLY = 'ugly', 'стрёмный'
        NERVOUS = 'nervous', 'нервный'
        CALM = 'calm', 'спокойный'

    class LEVEL(models.TextChoices):
        BEGINNER = 'beginner', 'новичок'
        AMATEUR = 'amateur', 'любитель'
        ADVANCED = 'advanced', 'продвинутый'
        EXPERT = 'expert', 'эксперт'
        LEGEND = 'legend', 'легенда'

    class ROLE(models.TextChoices):
        PLAYER_ROLE = 'player', 'игрок'
        REFEREE_ROLE = 'referee', 'судья'
        PR_ROLE = 'player_and_referee', 'игрок и судья'
        TRAINER = 'trainer', 'тренер'
        OTHER_ROLE = 'other', 'другая роль'

    searchable = models.SmallIntegerField(default=SEARCHABLE.YES, choices=SEARCHABLE.choices,
                                          verbose_name='Доступность для вызова другими игроками')
    middle_name = models.CharField(max_length=150, null=True, blank=True, verbose_name='Отчество')
    birthday = models.DateField(null=True, blank=True, verbose_name='День рождения')
    sex = models.SmallIntegerField(null=True, blank=True, choices=SEX.choices, verbose_name='Пол')
    about = models.TextField(null=True, blank=True, verbose_name='Обо мне')
    photo = models.ImageField(upload_to='players_photo', null=True, blank=True, verbose_name='Аватар')
    role = models.CharField(max_length=20, choices=ROLE.choices, default=ROLE.PLAYER_ROLE, verbose_name='Роль')
    skill_level = models.CharField(max_length=50, default=LEVEL.AMATEUR, choices=LEVEL.choices,
                                   verbose_name='Уровень игры')
    playstyle = models.CharField(max_length=50, null=True, blank=True, choices=STYLE.choices, verbose_name='Стиль игры')
    hand = models.SmallIntegerField(default=HAND.RIGHT, choices=HAND.choices, verbose_name='Игровая рука')
    phone_number = models.CharField(max_length=30, null=True, blank=True, verbose_name='Номер телефона')
    telegram_nick = models.CharField(max_length=65, null=True, blank=True, verbose_name='Никнейм в телеграмме')
    city = models.ForeignKey('additions.City', on_delete=models.CASCADE, related_name='player_city', null=True,
                             verbose_name='Город')
    ip = models.GenericIPAddressField(null=True, blank=True, verbose_name='ip-адрес')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания записи')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения записи')

    class Meta:
        verbose_name_plural = 'Игроки'
        verbose_name = 'Игрок'

    def get_absolute_url(self):
        return reverse('players:player_info', kwargs={'username': self.username})

    def __str__(self):
        return f'{self.username}'


User = get_user_model()


class Rating(models.Model):
    """Model has rating for each player depend on date"""

    player = models.ForeignKey(Player, on_delete=models.CASCADE, related_name='rating_player')
    rating_date = models.DateField(default=timezone.now, verbose_name='Дата')
    rating = models.DecimalField(decimal_places=1, max_digits=5, default=1000.0, validators=[MinValueValidator(0)],
                                 verbose_name='Рейтинг')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания записи')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения записи')

    class Meta:
        ordering = ['rating_date']
        verbose_name_plural = 'Рейтинги игрока'
        verbose_name = 'Рейтинг игрока'

    def __str__(self):
        return f'Рейтинг {self.player} на {self.rating_date}: {self.rating}.'


class Team(models.Model):
    """Model has info about table-tennis team"""

    name = models.CharField(max_length=100, verbose_name='Имя команды')
    logo = models.ImageField(upload_to='teams_logo', null=True, blank=True, verbose_name='Логотип команды')
    description = models.TextField(null=True, blank=True, verbose_name='Описание команды')
    caption = models.ForeignKey(Player, on_delete=models.CASCADE, related_name='team_caption',
                                verbose_name='Капитан команды')
    members = models.ManyToManyField(Player, related_name='team_members', verbose_name='Участники команды')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания записи')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения записи')

    class Meta:
        verbose_name_plural = 'Команды'
        verbose_name = 'Команда'

    def __str__(self):
        return f'Команда {self.name}'


class Doubles(models.Model):
    """Model has info about 2 team players which is actually one pair"""

    class TYPE(models.IntegerChoices):
        MM = 1, 'мужская пара'
        FF = 2, 'женская пара'
        MF = 3, 'смешанная пара'

    player_1 = models.ForeignKey(Player, on_delete=models.CASCADE, related_name='doubles_player_1',
                                 verbose_name='1-ый игрок')
    player_2 = models.ForeignKey(Player, on_delete=models.CASCADE, related_name='doubles_player_2',
                                 verbose_name='2-ой игрок')
    pair_type = models.PositiveSmallIntegerField(choices=TYPE.choices, verbose_name='Тип пары')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания записи')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения записи')

    class Meta:
        verbose_name_plural = 'Пары'
        verbose_name = 'Пара'

    def __str__(self):
        return f'Пара #{self.pk}'


class ChatMessage(models.Model):
    """The model has info about chat message"""

    sender = models.ForeignKey('players.Player', on_delete=models.CASCADE, related_name='chatmessage_sender',
                               verbose_name='Отправитель сообщения')
    receiver = models.ForeignKey('players.Player', on_delete=models.CASCADE, related_name='chatmessage_receiver',
                                 verbose_name='Получатель сообщения')
    date_time = models.DateTimeField(default=timezone.now, verbose_name='Дата и время отправки сообщения')
    content = models.CharField(max_length=4096, verbose_name='Сообщение')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания записи')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения записи')

    class Meta:
        verbose_name_plural = 'Чаты'
        verbose_name = 'Чат'

    def __str__(self):
        return f'Сообщение #{self.pk}'

    def clean(self):
        # Checking if sender is not receiver
        if self.sender == self.receiver:
            raise ValidationError('sender and receiver must be different.')

    def save(self, *args, **kwargs):
        self.clean()  # Call clean() before save()
        super().save(*args, **kwargs)


class SearchPartner(models.Model):
    """Model is for searching partner"""
    class STATUS(models.TextChoices):
        ACTIVE = 'active', 'активно'
        COMPLETED = 'completed', 'завершено'
        CANCELED = 'canceled', 'отменено'

    class GAMETYPE(models.TextChoices):
        SINGLE = 'singles', 'одиночная'
        DOUBLES = 'doubles', 'парная'
        TEAM = 'team', 'командная'

    player = models.ForeignKey('players.Player', on_delete=models.CASCADE, verbose_name="Пользователь")
    search_date = models.DateTimeField(auto_now_add=True, verbose_name="Дата поиска")
    status = models.CharField(max_length=20, choices=STATUS.choices, default=STATUS.ACTIVE,
                              verbose_name="Статус поиска")
    game_type = models.CharField(max_length=20, choices=GAMETYPE.choices, verbose_name="Тип игры")
    min_rating = models.IntegerField(null=True, blank=True, verbose_name="Минимальный рейтинг")
    max_rating = models.IntegerField(null=True, blank=True, verbose_name="Максимальный рейтинг")
    min_age= models.IntegerField(null=True, blank=True, verbose_name="Минимальный возраст")
    max_age = models.IntegerField(null=True, blank=True, verbose_name="Максимальный возраст")
    skill_level = models.CharField(max_length=50, null=True, blank=True, choices=Player.LEVEL.choices,
                                   verbose_name='Уровень игры')
    playstyle = models.CharField(max_length=50, null=True, blank=True, choices=Player.STYLE.choices,
                                 verbose_name='Стиль игры')
    hand = models.SmallIntegerField(null=True, blank=True, choices=Player.HAND.choices, verbose_name='Игровая рука')
    city = models.ForeignKey('additions.City', on_delete=models.CASCADE, verbose_name="Город")
    message = models.TextField(blank=True, null=True, verbose_name="Сообщение")

    class Meta:
        verbose_name = "Поиск партнёра"
        verbose_name_plural = "Поиски партнёров"

    def __str__(self):
        return f"{self.player.username} - {self.get_game_type_display()} - {self.status}"

templates/players/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Результаты игр{% endblock %}
{% block content %}
<!-- Фильтры для рейтинга -->
{% include 'players/players_filter.html' %}


<!-- Таблица рейтинга -->
<div class="my-2 col-12 col-md-6 col-lg-4 card">
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Игрок</th>
                <th scope="col">Рейтинг</th>
                <th scope="col">Позиция</th>
            </tr>
        </thead>
        <tbody>
        {% for player in page_obj %}
            <tr>
                <th scope="row">{{ forloop.counter|add:start }}</th>
                <td>
                    <a class="navbar-footer nav-link" href="{% url 'players:player_info' player.username %}">{{ player.username }}</a>
                </td>
                <td>{{ player.latest_rating }}</td>
                <td>{{ player.position }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% include 'paginator_with_filter.html' %}
</div>


{% endblock content%}

templates/players/notifications.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {{ title }} {% endblock %}
{% block content %}

<div class="container-fluid">
    <div class="row">
        <!-- Notification' navigation menu -->
        <nav class="col-md-3 col-lg-2 d-md-block bg-white sidebar mt-2">
            <div class="position-sticky">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a href="{% url 'players:notifications' %}" class="btn btn-info text-uppercase text-white m-1 d-flex justify-content-between w-100">
                            <span>Все</span>
                            <span class="badge bg-light text-dark">{{ unread_count }}</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'players:invitation_notifications' %}" class="btn btn-info text-uppercase text-white m-1 d-flex justify-content-between w-100">
                            <span>Приглашения</span>
                            <span class="badge bg-light text-dark">{{ invitation_content_count }}</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'players:event_notifications' %}" class="btn btn-info text-uppercase text-white m-1 d-flex justify-content-between w-100">
                            <span>События</span>
                            <span class="badge bg-light text-dark">{{ event_content_count }}</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="btn btn-info text-uppercase text-white m-1 d-flex justify-content-between w-100">
                            <span>Турниры</span>
                            <span class="badge bg-light text-dark">-</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'players:clubs_notifications' %}" class="btn btn-info text-uppercase text-white m-1 d-flex justify-content-between w-100">
                            <span>Клубы</span>
                            <span class="badge bg-light text-dark">{{ club_notification_count }}</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="btn btn-info text-uppercase text-white m-1 d-flex justify-content-between w-100">
                            <span>Игры</span>
                            <span class="badge bg-light text-dark">-</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="btn btn-info text-uppercase text-white m-1 d-flex justify-content-between w-100">
                            <span>Рейтинг</span>
                            <span class="badge bg-light text-dark">-</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'players:news_notifications' %}" class="btn btn-info text-uppercase text-white m-1 d-flex justify-content-between w-100">
                            <span>Новости</span>
                            <span class="badge bg-light text-dark">{{ news_notification_count }}</span>
                        </a>
                    </li>
                </ul>
            </div>
        </nav>

        <!-- Main content -->
        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
            <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 border-bottom">
                <h1 class="h2">{{ title }}</h1>
            </div>
            <!-- Notification list -->
            <ul class="list-group list-group-flush mb-2">
                {% for notification in custom_notifications %}
                    {% if notification.unread %}
                    <li class="list-group-item d-flex justify-content-between align-items-center" id="{{ notification.pk }}" data-action="{{ notification.action }}" data-notification-pk="{{ notification.pk }}"  style="background-color:#ECF6FE">
                    {% else %}
                    <li class="list-group-item d-flex justify-content-between align-items-center bg-light" id="{{ notification.pk }}" data-action="{{ notification.action }}" data-notification-pk="{{ notification.pk }}">
                    {% endif %}
                        <div>
                            <span class="badge bg-secondary">{{ notification.timestamp }}</span>
                            {% if notification.target.invitation %}
                                <span>{{ notification.verb }}</span>
                                <a href="{% url 'players:player_info' username=notification.actor.username %}">{{ notification.actor.username }}</a>.
                                {% if notification.target.status == 'active' %}
                                    <span id="result-for-reaction-to-invitation-{{ notification.target.pk }}" data-invitation-pk="{{ notification.target.pk }}" data-player-pk="{{ notification.actor.pk }}">
                                        Вы можете <a href="{% url 'events:accept_invitation' invitation_pk=notification.target.pk %}">согласиться на встречу</a> и договорить о подробностях, или <a href="#" class="reject-invitation">отказаться</a>.
                                        <div id="rejection-reason-input" style="display: none;" class="rejection-form">
                                            <input type="text" id="rejection-reason" class="form-control my-2" placeholder="Причина (необязательно)">
                                            <button class="btn btn-secondary send-rejection">Отказать</button>
                                        </div>
                                    </span>
                                {% elif notification.target.status == 'rejected' %}
                                    {% if notification.description %}
                                        <span>Причина: "{{ notification.description }}".</span>
                                    {% endif %}
                                {% endif %}
                            {% endif %}

                            {% if notification.target.participants %}
                                <a href="{% url 'players:player_info' username=notification.actor.username %}">{{ notification.actor.username }}</a>
                                    <span id="result-for-reaction-to-invitation-{{ notification.target.pk }}" data-invitation-pk="{{ notification.target.pk }}" data-player-pk="{{ notification.actor.pk }}">
                                        {{ notification.verb }} <a href="{% url 'events:event' event_pk=notification.target.pk %}">{{ notification.target.name }}</a>.
                                    </span>
                            {% endif %}
                            {% if notification.target.owner %}
                                    <span id="result-for-reaction-to-invitation-{{ notification.target.pk }}" data-invitation-pk="{{ notification.target.pk }}" data-player-pk="{{ notification.actor.pk }}">
                                        {{ notification.verb }}.
                                    </span>
                            {% endif %}
                            {% if notification.target.content %}
                                    <span id="result-for-reaction-to-invitation-{{ notification.target.pk }}" data-invitation-pk="{{ notification.target.pk }}" data-player-pk="{{ notification.actor.pk }}">
                                        {{ notification.verb }}.
                                    </span>
                            {% endif %}
                        </div>
                        <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close" onclick="deleteNotification({{ notification.id }})"></button>
                    </li>
                {% endfor %}
            </ul>
            {% include "paginator_with_filter.html"  %}
        </main>
    </div>
</div>

{% include 'players/ajax_notifications_in_notifications.html' %}

{% endblock content%}

templates/players/player_info.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {{ player.username }} {% endblock %}
{% block content %}
<div class="mb-4 col-12 col-md-6 col-lg-4">
    <div>
        <div class="d-flex justify-content-center">
            <h1 class="mb-2">{{ player.username }}</h1>
        </div>
        <div class="d-flex justify-content-center">
            <img class="mb-4" src="{% if player.photo %}{{ player.photo.url }}
                                  {% else %}{% static 'img/default/ava_default.png' %}
                                  {% endif %}" width="150px" height="150px">
        </div>
        <table class="table table-striped">
            <tbody>

            {% if player.first_name %}
            <tr>
                <td class="fw-bold align-middle">Имя</td>
                <td>{{ player.first_name }}</td>
            </tr>
            {% endif %}

            {% if player.last_name %}
            <tr>
                <td class="fw-bold align-middle">Фамилия</td>
                <td>{{ player.last_name }}</td>
            </tr>
            {% endif %}

            <tr>
                <td class="fw-bold align-middle">Позиция в рейтинге</td>
                <td>{{ player_last_position }}</td>
            </tr>

            <tr>
                <td class="fw-bold align-middle">Рейтинг</td>
                <td>{{ player_last_rating }}</td>
            </tr>

            <tr>
                <td class="fw-bold align-middle">На сайте с</td>
                <td>{{ player.date_joined }}</td>
            </tr>

            {% if player.about %}
            <tr>
                <td class="fw-bold align-middle">Обо мне</td>
                <td>{{ player.about }}</td>
            </tr>
            {% endif %}

            {% if player.city %}
            <tr>
                <td class="fw-bold align-middle">Страна</td>
                <td>{{ player.city.country.name }}</td>
            </tr>
            <tr>
                <td class="fw-bold align-middle">Город</td>
                <td>{{ player.city.name }}</td>
            </tr>
            {% endif %}

            {% if player.role %}
            <tr>
                <td class="fw-bold align-middle">Роль</td>
                <td>{{ player.get_role_display }}</td>
            </tr>
            {% endif %}

            {% if player.skill_level %}
            <tr>
                <td class="fw-bold align-middle">Уровень игры</td>
                <td>{{ player.get_skill_level_display }}</td>
            </tr>
            {% endif %}

            {% if player.playstyle %}
            <tr>
                <td class="fw-bold align-middle">Стиль игры</td>
                <td>{{ player.get_playstyle_display }}</td>
            </tr>
            {% endif %}

            <tr>
                <td class="fw-bold align-middle">Игровая рука</td>
                <td>{{ player.get_hand_display }}</td>
            </tr>

            </tbody>
        </table>
    </div>
</div>

<!--Отображение графика рейтинга-->
<div class="mb-4 mt-4 col-12 col-md-6 col-lg-4 d-flex justify-content-center">
    {% include 'players/graphical_rating.html' %}
</div>

{% endblock content%}

templates/players/players_filter.html
<div class="mb-4 col-12 col-md-6 col-lg-4">
    <h4>Параметры поиска</h4>
    {% if rating_page %}
    <form method="GET" action="{% url 'players:index' %}">
    {% elif search_partner_page %}
    <form method="GET" action="{% url 'events:search_partner' %}">
    {% endif %}
       <table class="registration-form">
        <tr>
            <div style="display: flex; align-items: center;">
                <label for="{{ form.username.id_for_label }}">Игрок:</label>
                 {{ form.username }}
            </div>

        </tr>

        <tr>
            <div style="display: flex; align-items: center;">
                <label for="{{ form.min_rating.id_for_label }}">Рейтинг: от</label>
                 {{ form.min_rating }}
                <label for="{{ form.max_rating.id_for_label }}">до</label>
                {{ form.max_rating }}
            </div>
        </tr>

        <tr>
            <div style="display: flex; align-items: center;">
                <label for="{{ form.min_rating.id_for_label }}">Возраст: от</label>
                 {{ form.min_age }}
                <label for="{{ form.max_rating.id_for_label }}">до</label>
                {{ form.max_age }}
            </div>
        </tr>

        <tr>
            <td>
                <label for="{{ form.has_photo.id_for_label }}">Фото:</label>
            </td>
            <td valign="top">
                {{ form.has_photo }}
            </td>
        </tr>

        <tr>
            <td>
                <label for="{{ form.sex.id_for_label }}">Пол:</label>
            </td>
            <td valign="top">
                {{ form.sex }}
            </td>
        </tr>

        <tr>
            <td>
                <label for="{{ form.city.id_for_label }}">Город:</label>
            </td>
            <td valign="top">
                {{ form.city }}
            </td>
        </tr>

        <tr>
            <td>
                <label for="{{ form.club.id_for_label }}">Клуб:</label>
            </td>
            <td valign="top">
                {{ form.club }}
            </td>
        </tr>

        <tr>
            <td>
                <label for="{{ form.role.id_for_label }}">Роль:</label>
            </td>
            <td valign="top">
                {{ form.role }}
            </td>
        </tr>

        <tr>
            <td>
                <label for="{{ form.skill_level.id_for_label }}">Уровень игры:</label>
            </td>
            <td valign="top">
                {{ form.skill_level }}
            </td>
        </tr>

        <tr>
            <td>
                <label for="{{ form.playstyle.id_for_label }}">Стиль игры:</label>
            </td>
            <td valign="top">
                {{ form.playstyle }}
            </td>
        </tr>

        <tr>
            <td>
                <label for="{{ form.hand.id_for_label }}">Игровая рука:</label>
            </td>
            <td>
                {{ form.hand }}
            </td>
        </tr>
    </table>

        <div class="my-2" style="background-color: rgba(255, 0, 0, 0.1);">
            {{ form.username.errors }}
            {{ form.photo.errors }}
            {{ form.min_rating.errors }}
            {{ form.max_rating.errors }}
            {{ form.sex.errors }}
            {{ form.min_age.errors }}
            {{ form.max_age.errors }}
            {{ form.city.errors }}
            {{ form.role.errors }}
            {{ form.skill_level.errors }}
            {{ form.playstyle.errors }}
            {{ form.has_hand.errors }}
        </div>

        <button type="submit" class="btn btn-secondary">Применить фильтры</button>
    </form>
</div>