clubs/urls.py
from django.urls import path
from . import views

app_name = 'clubs'

urlpatterns = [
    path('', views.ClubList.as_view(), name='index'),
    path('club/<int:pk>/', views.ClubView.as_view(), name='club'),
    path('club/<int:club_pk>/news_list/', views.ClubNewsListView.as_view(), name='club_list_news'),
    path('club/<int:club_pk>/news/<int:pk>/', views.ClubNewsDetailView.as_view(), name='club_news'),
    path('club/<int:pk>/players/', views.ClubPlayersList.as_view(), name='club_players'),
    path('create/', views.ClubCreationView.as_view(), name='create_club'),
    path('edit_club/<int:pk>/', views.UpdateClubView.as_view(), name='edit_club'),
    path('my_clubs/', views.MyClubList.as_view(), name='my_clubs'),
    path('participation_in_clubs/', views.ParticipationClubList.as_view(), name='participation_in_clubs'),
    path('add_potential_members/<int:club_pk>/', views.add_player_to_potential_club_members, name='add_potential_members'),
    path('potential_members/<int:club_pk>/', views.potential_members, name='potential_members'),
    path('add_to_open_club_members/<int:club_pk>/', views.add_to_open_club_members, name='add_to_open_club_members'),
    path('to_real_members/<int:club_pk>/<int:player_pk>/', views.add_potential_club_member_to_real_members, name='to_real_members'),
    path('reject_potential_member/<int:club_pk>/<int:player_pk>/', views.reject_potential_member, name='reject_potential_member'),
    path('potential_club_news_list/<int:club_pk>/', views.potential_club_news_list, name='potential_club_news_list'),
    path('potential_club_news/<int:club_pk>/<int:pk>/', views.PotentialClubNewsDetailView.as_view(), name='potential_club_news'),
    path('to_club_news/<int:club_pk>/<int:news_pk>/', views.add_potential_club_news, name='to_club_news'),
    path('reject_club_news/<int:club_pk>/<int:news_pk>/', views.reject_potential_club_news, name='reject_club_news'),
]

events/urls.py
from django.urls import path
from . import views

app_name = 'events'

urlpatterns = [
    path('', views.EventListView.as_view(), name='events'),
    path('my_events/', views.MyEventListView.as_view(), name='my_events'),
    path('event/<int:event_pk>/', views.show_event, name='event'),
    path('join_the_club/<int:event_pk>/', views.join_the_club, name='join_the_club'),
    path('search_partner/', views.get_search_partner_page, name='search_partner'),
    path('create_event/', views.EventCreationView.as_view(), name='create_event'),
    path('update_event/<int:pk>/', views.update_event, name='update_event'),
    path('invite_to_play/<int:player_pk>/', views.invite_to_play, name='invite_to_play'),
    path('reject_invitation/<int:invitation_pk>/<int:player_pk>/', views.reject_invitation, name='reject_invitation'),
    path('accept_invitation/<int:invitation_pk>/', views.accept_invitation, name='accept_invitation'),

    ]

games/urls.py
from django.urls import path
from . import views

app_name = 'games'

urlpatterns = [
    path('', views.get_games_index_page, name='index'),
    path('tournaments/', views.get_tournaments, name='tournaments'),
]

news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.get_news_index_page, name='index'),
    path('rules', views.get_rules, name='rules'),
    path('about_us', views.about_us, name='about_us'),
    path('news', views.PublicNewsListView.as_view(), name='public_news_list'),
    path('news/<int:pk>/', views.PublicNewsDetailView.as_view(), name='get_the_open_news'),
    path('creating_news/', views.NewsCreationView.as_view(), name='creating_news'),
    path('updating_news/<int:pk>/', views.UpdateNewsView.as_view(), name='updating_news'),
    path('like_news/<int:news_pk>/', views.like_news, name='like_news'),
]

players/urls.py
from django.urls import path
from . import views

app_name = 'players'

urlpatterns = [
    path('', views.get_players_index_page, name='index'),
    path('player_info/<slug:username>/', views.get_player_info, name='player_info'),
    path('plot_rating_data/<slug:username>/', views.plot_rating_graph, name='plot_rating_data'),
    # path('change_rating/', views.change_rating, name='change_rating'),
    path('registration/', views.register_view, name='registration'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile, name='profile'),

    path('notifications/', views.AllNotificationListView.as_view(), name='notifications'),
    path('notifications/invitation/', views.InvitationNotificationListView.as_view(), name='invitation_notifications'),
    path('notifications/events/', views.EventNotificationListView.as_view(), name='event_notifications'),
    path('notifications/clubs/', views.ClubNotificationListView.as_view(), name='clubs_notifications'),
    path('notifications/news/', views.NewsNotificationListView.as_view(), name='news_notifications'),
    path('notifications/actions/', views.NotificationActions.as_view(), name='notifications_actions'),

    path('validate_email/', views.validate_email, name='validate_email'),
    path('validate_username/', views.validate_username, name='validate_username'),
    path('validate_password_view/', views.validate_password_view, name='validate_password_view'),

    # path('api/v1/players_list/', views.PlayersInfoAPIView.as_view(), name='api_players_list'),
    path('api/v1/api_players_rating/', views.PlayersRatingAPIView.as_view(), name='api_players_rating'),
]

ttennis/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar
import notifications.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('', include('news.urls', namespace='news')),
    path('players/', include('players.urls', namespace='players')),
    path('events/', include('events.urls', namespace='events')),
    path('games/', include('games.urls', namespace='games')),
    path('clubs/', include('clubs.urls', namespace='clubs')),
    path('additions/', include('additions.urls', namespace='additions')),
    path('tournaments/', include('tournaments.urls', namespace='tournaments')),
]


# For debug_toolbar
if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls))
    ]

# For media files
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
{% load static %}
{% load notifications_tags %}
{% notifications_unread as unread_count %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=1">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
<!--    Notification API-->
<!--    <script src="{% static 'notifications/notify.js' %}" type="text/javascript"></script>-->
<!--    {% register_notify_callbacks callbacks='fill_notification_list,fill_notification_badge' %}-->
    {% block javascripts %}{% endblock %}
    <link href="{% static 'img/brand/favicon/spinpoint-favicon-color.png' %}" rel="shortcut icon" type="image/png"/>
    <title>SpinPoint :: {% block title %}{% endblock %}</title>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-xl">
        <a class="navbar-brand mx-2" href="{% url 'news:index' %}">
            <img src="{% static 'img/brand/spinpoint-high-resolution-logo-white-transparent.svg' %}" alt="SpinPoint"
                 class="logo-img">
        </a>
        <button class="navbar-toggler mx-1" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="p-2">
                    <a class="text-uppercase" aria-current="page" href="{% url 'news:index' %}">Главная</a>
                </li>
                <li class="p-2">
                    <a class="text-uppercase" aria-current="page" href="{% url 'players:index' %}">Рейтинг</a>
                </li>
                <li class="p-2">
                    <a class="text-uppercase" aria-current="page" href="{% url 'games:index' %}">Результаты игр</a>
                </li>
                <li class="p-2">
                    <a class="text-uppercase" href="{% url 'games:tournaments' %}">Турниры</a>
                </li>

                <!-- Additional club's menu -->
                {% if user.is_authenticated %}
                    <li class="p-2 nav-item dropdown">
                        <a class="text-uppercase dropdown-toggle" data-bs-toggle="dropdown" href="{% url 'clubs:index' %}">Клубы</a>
                        <ul class="dropdown-menu dropdown-menu-dark">
                          <li><a class="dropdown-item" href="{% url 'clubs:index' %}">Все</a></li>
                          <li><a class="dropdown-item" href="{% url 'clubs:my_clubs' %}">Мои</a></li>
                          <li><a class="dropdown-item" href="{% url 'clubs:participation_in_clubs' %}">С моим участием</a></li>
                          <li><hr class="dropdown-divider"></li>
                          <li><a class="dropdown-item" href="{% url 'clubs:create_club' %}">Создать новый</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li class="p-2">
                        <a class="text-uppercase" href="{% url 'clubs:index' %}">Клубы</a>
                    </li>
                {% endif %}
                <li class="p-2">
                    <a class="text-uppercase" href="{% url 'events:search_partner' %}">Найти партнёра</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="p-2 nav-item dropdown">
                        <a class="text-uppercase dropdown-toggle" data-bs-toggle="dropdown" href="{% url 'events:events' %}">События</a>
                        <ul class="dropdown-menu dropdown-menu-dark">
                          <li><a class="dropdown-item" href="{% url 'events:events' %}">Все</a></li>
                          <li><a class="dropdown-item" href="{% url 'events:my_events' %}">Мои</a></li>
                          <li><hr class="dropdown-divider"></li>
                          <li><a class="dropdown-item" href="{% url 'events:create_event' %}">Создать событие</a></li>
                        </ul>
                    </li>
                {% endif %}
                <li class="p-2">
                    <a class="text-uppercase" href="{% url 'news:rules' %}">Правила</a>
                </li>
                <li class="p-2">
                    <a class="text-uppercase" href="{% url 'news:about_us' %}">О нас</a>
                </li>
                {% if user.is_superuser %}
                    <li class="p-2">
                        <a class="text-uppercase" href="{% url 'admin:index' %}">Админка</a>
                    </li>
                {% endif %}
            </ul>
            <div class="ms-auto">
                {% if user.is_authenticated %}
                    <a href="{% url 'players:notifications' %}" class="m-1 position-relative"><img src="{% static 'img/bell-solid.svg' %}" width="30px"></a>
                        {% if unread_count %}
                            <span class="position-absolute top-5 end-4 translate-middle badge-container mt-2 me-5 pe-2">
                                <span class="badge rounded-pill bg-danger"><strong>{{ unread_count }}</strong></span>
                            </span>
                        {% endif %}
                    <a href="{% url 'players:profile' %}" class="m-3 position-relative"><img src="{% static 'img/user.svg' %}" width="40px"></a>
                    <a href="{% url 'players:logout' %}" class="btn btn-secondary text-white m-1">Выйти</a>
                {% else %}
                <a href="{% url 'players:login' %}" class="btn btn-info text-uppercase text-white m-1">Войти</a>
                <a href="{% url 'players:registration' %}" class="btn btn-primary text-uppercase m-1">Присоединиться</a>
                {% endif %}
            </div>
        </div>
    </nav>
</header>


<section class="">
    <div class="container-fluid">
        <div class="row">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</section>

<footer class="py-3 my-4">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 px-0">
                <ul class="nav navbar-footer justify-content-center border-bottom border-top py-1 my-3 fw-bold">
                    <li class="nav-item"><a href="{% url 'news:index' %}"
                                            class="nav-link px-2 navbar-footer text-uppercase">Главная</a></li>
                    <li class="nav-item"><a href="{% url 'players:index' %}"
                                            class="nav-link px-2 navbar-footer text-uppercase">Рейтинг</a></li>
                    <li class="nav-item"><a href="{% url 'games:index' %}"
                                            class="nav-link px-2 navbar-footer text-uppercase">Результаты игр</a></li>
                    <li class="nav-item"><a href="{% url 'games:tournaments' %}"
                                            class="nav-link px-2 navbar-footer text-uppercase">Турниры</a></li>
                    <li class="nav-item"><a href="{% url 'clubs:index' %}"
                                            class="nav-link px-2 navbar-footer text-uppercase">Клубы</a></li>
                    <li class="nav-item"><a href="{% url 'events:search_partner' %}"
                                            class="nav-link px-2 navbar-footer text-uppercase">Найти партнёра</a></li>
                    <li class="nav-item"><a href="{% url 'news:rules' %}"
                                            class="nav-link px-2 navbar-footer text-uppercase">Правила</a></li>
                    <li class="nav-item"><a href="{% url 'news:about_us' %}"
                                            class="nav-link px-2 navbar-footer text-uppercase">О нас</a></li>
                </ul>
                <p class="text-center">
                    <a href="{% url 'news:index' %}">
                        <img src="{% static 'img/brand/spinpoint-high-resolution-logo-transparent_green.svg' %}"
                             alt="logo" class="logo-img">
                    </a>
                </p>
            </div>
        </div>
    </div>
</footer>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

templates/paginator.html
<div class="d-flex justify-content-center">
  {% if page_obj.has_other_pages %}
    <nav aria-label="Page navigation example">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?&page={{ page_obj.previous_page_number }}" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a>
        </li>
      {% endif %}
      {% for p in page_obj.paginator.page_range %}
        {% if page_obj.number == p %}
          <li class="page-item">
            <a class="page-link active" aria-current="page" href="?&page={{ p }}">{{ p }}</a>
          </li>
        {% elif p > page_obj.number|add:-3  and p < page_obj.number|add:3%}
          <li class="page-item">
            <a class="page-link" href="?page={{ p }}">{{ p }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?&page={{ page_obj.next_page_number }}" aria-label="Next"><span aria-hidden="true">&raquo;</span></a>
        </li>
      {% endif %}
    </ul>
  </nav>
  {% endif %}
</div>

templates/paginator_with_filter.html
<div class="d-flex justify-content-center">
  {% if page_obj.has_other_pages %}
    <nav aria-label="Page navigation example">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?{{ request.GET.urlencode }}&page={{ page_obj.previous_page_number }}" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a>
        </li>
      {% endif %}
      {% for p in page_obj.paginator.page_range %}
        {% if page_obj.number == p %}
          <li class="page-item">
            <a class="page-link active" aria-current="page" href="?{{ request.GET.urlencode }}&page={{ p }}">{{ p }}</a>
          </li>
        {% elif p > page_obj.number|add:-3  and p < page_obj.number|add:3%}
          <li class="page-item">
            <a class="page-link" href="?{{ request.GET.urlencode }}&page={{ p }}">{{ p }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?{{ request.GET.urlencode }}&page={{ page_obj.next_page_number }}" aria-label="Next"><span aria-hidden="true">&raquo;</span></a>
        </li>
      {% endif %}
    </ul>
  </nav>
  {% endif %}
</div>