clubs/urls.py
from django.urls import path
from . import views

app_name = 'clubs'

urlpatterns = [
    path('', views.ClubList.as_view(), name='index'),
    path('club/<int:pk>/', views.ClubView.as_view(), name='club'),
    path('club/<int:club_pk>/news_list/', views.ClubNewsListView.as_view(), name='club_list_news'),
    path('club/<int:club_pk>/news/<int:pk>/', views.ClubNewsDetailView.as_view(), name='club_news'),
    path('club/<int:pk>/players/', views.ClubPlayersList.as_view(), name='club_players'),
    path('create/', views.ClubCreationView.as_view(), name='create_club'),
    path('edit_club/<int:pk>/', views.UpdateClubView.as_view(), name='edit_club'),
    path('my_clubs/', views.MyClubList.as_view(), name='my_clubs'),
    path('participation_in_clubs/', views.ParticipationClubList.as_view(), name='participation_in_clubs'),
    path('add_potential_members/<int:club_pk>/', views.add_player_to_potential_club_members, name='add_potential_members'),
    path('potential_members/<int:club_pk>/', views.potential_members, name='potential_members'),
    path('add_to_open_club_members/<int:club_pk>/', views.add_to_open_club_members, name='add_to_open_club_members'),
    path('to_real_members/<int:club_pk>/<int:player_pk>/', views.add_potential_club_member_to_real_members, name='to_real_members'),
    path('reject_potential_member/<int:club_pk>/<int:player_pk>/', views.reject_potential_member, name='reject_potential_member'),
    path('potential_club_news_list/<int:club_pk>/', views.potential_club_news_list, name='potential_club_news_list'),
    path('potential_club_news/<int:club_pk>/<int:pk>/', views.PotentialClubNewsDetailView.as_view(), name='potential_club_news'),
    path('to_club_news/<int:club_pk>/<int:news_pk>/', views.add_potential_club_news, name='to_club_news'),
    path('reject_club_news/<int:club_pk>/<int:news_pk>/', views.reject_potential_club_news, name='reject_club_news'),
]

events/urls.py
from django.urls import path
from . import views

app_name = 'events'

urlpatterns = [
    path('', views.EventListView.as_view(), name='events'),
    path('my_events/', views.MyEventListView.as_view(), name='my_events'),
    path('event/<int:event_pk>/', views.show_event, name='event'),
    path('join_the_club/<int:event_pk>/', views.join_the_club, name='join_the_club'),
    path('search_partner/', views.get_search_partner_page, name='search_partner'),
    path('create_event/', views.EventCreationView.as_view(), name='create_event'),
    path('update_event/<int:pk>/', views.update_event, name='update_event'),
    path('invite_to_play/<int:player_pk>/', views.invite_to_play, name='invite_to_play'),
    path('reject_invitation/<int:invitation_pk>/<int:player_pk>/', views.reject_invitation, name='reject_invitation'),
    path('accept_invitation/<int:invitation_pk>/', views.accept_invitation, name='accept_invitation'),

    ]

news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.get_news_index_page, name='index'),
    path('rules', views.get_rules, name='rules'),
    path('about_us', views.about_us, name='about_us'),
    path('news', views.PublicNewsListView.as_view(), name='public_news_list'),
    path('news/<int:pk>/', views.PublicNewsDetailView.as_view(), name='get_the_open_news'),
    path('creating_news/', views.NewsCreationView.as_view(), name='creating_news'),
    path('updating_news/<int:pk>/', views.UpdateNewsView.as_view(), name='updating_news'),
    path('like_news/<int:news_pk>/', views.like_news, name='like_news'),
]

players/urls.py
from django.urls import path
from . import views

app_name = 'players'

urlpatterns = [
    path('', views.get_players_index_page, name='index'),
    path('player_info/<slug:username>/', views.get_player_info, name='player_info'),
    path('plot_rating_data/<slug:username>/', views.plot_rating_graph, name='plot_rating_data'),
    # path('change_rating/', views.change_rating, name='change_rating'),
    path('registration/', views.register_view, name='registration'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile, name='profile'),

    path('notifications/', views.AllNotificationListView.as_view(), name='notifications'),
    path('notifications/invitation/', views.InvitationNotificationListView.as_view(), name='invitation_notifications'),
    path('notifications/events/', views.EventNotificationListView.as_view(), name='event_notifications'),
    path('notifications/clubs/', views.ClubNotificationListView.as_view(), name='clubs_notifications'),
    path('notifications/news/', views.NewsNotificationListView.as_view(), name='news_notifications'),
    path('notifications/actions/', views.NotificationActions.as_view(), name='notifications_actions'),

    path('validate_email/', views.validate_email, name='validate_email'),
    path('validate_username/', views.validate_username, name='validate_username'),
    path('validate_password_view/', views.validate_password_view, name='validate_password_view'),

    # path('api/v1/players_list/', views.PlayersInfoAPIView.as_view(), name='api_players_list'),
    path('api/v1/api_players_rating/', views.PlayersRatingAPIView.as_view(), name='api_players_rating'),
]

ttennis/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar
import notifications.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('', include('news.urls', namespace='news')),
    path('players/', include('players.urls', namespace='players')),
    path('events/', include('events.urls', namespace='events')),
    path('games/', include('games.urls', namespace='games')),
    path('clubs/', include('clubs.urls', namespace='clubs')),
    path('additions/', include('additions.urls', namespace='additions')),
    path('tournaments/', include('tournaments.urls', namespace='tournaments')),
]


# For debug_toolbar
if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls))
    ]

# For media files
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

events/models.py
from django.db import models


class Event(models.Model):
    """For meetings players for game or training"""

    class STATUS(models.TextChoices):
        ACTIVE = 'active', 'активно'
        COMPLETED = 'completed', 'завершено'
        CANCELED = 'canceled', 'отменено'

    class OPEN(models.IntegerChoices):
        YES = 1, 'открытое'
        NO = 0, 'закрытое'

    name = models.CharField(max_length=255, verbose_name='Имя события')
    initiator = models.ForeignKey('players.Player', on_delete=models.CASCADE, related_name='event_initiator',
                                  verbose_name='Инициатор')
    participants = models.ManyToManyField('players.Player', related_name='event_participants',
                                          verbose_name='Участники встречи')
    allowed_participants = models.ManyToManyField('players.Player', blank=True,
                                                  related_name='event_allowed_participants',
                                                  verbose_name='Имеющие права игроки на участие во встрече')
    status = models.CharField(max_length=20, choices=STATUS.choices, default=STATUS.ACTIVE,
                              verbose_name="Статус события")
    is_open = models.SmallIntegerField(default=OPEN.YES, choices=OPEN.choices, verbose_name='Статус')
    start_date = models.DateField(null=True, blank=True, verbose_name='Дата и время начала встречи')
    start_time = models.TimeField(null=True, blank=True, verbose_name='Дата и время начала встречи')
    finish_date = models.DateField(null=True, blank=True, verbose_name='Дата и время завершения встречи')
    finish_time = models.TimeField(null=True, blank=True, verbose_name='Дата и время завершения встречи')
    club = models.ForeignKey('clubs.Club', on_delete=models.CASCADE, null=True, blank=True, related_name='event_club',
                             verbose_name='Клуб')
    city = models.ForeignKey('additions.City', on_delete=models.CASCADE, related_name='event_city',
                             null=True, blank=True, verbose_name='Город')
    addr = models.CharField(max_length=255, verbose_name='Адрес')
    description = models.TextField(null=True, blank=True, verbose_name='Описание')
    cover = models.ImageField(upload_to='news_covers', null=True, blank=True, verbose_name='Изображение')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания записи')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения записи')

    class Meta:
        verbose_name_plural = 'События'
        verbose_name = 'Событие'

    def __str__(self):
        return f'Событие {self.name}'


class EventComment(models.Model):
    """The model has info about comments of the meeting"""

    commenter = models.ForeignKey('players.Player', on_delete=models.CASCADE, related_name='eventcomment_commenter',
                                  verbose_name='Комментатор')
    meeting = models.ForeignKey(Event, on_delete=models.CASCADE, related_name='eventcomment_meeting',
                                verbose_name='Встреча')
    comment = models.TextField(verbose_name='Комментарий')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания записи')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения записи')

    class Meta:
        verbose_name_plural = 'Комментарии к встречам'
        verbose_name = 'Комментарий к встрече'

    def __str__(self):
        return f'Комментарий к встрече #{self.meeting}'


class Invitation(models.Model):
    """Needed to invite one player to another"""

    class STATUS(models.TextChoices):
        ACTIVE = 'active', 'активно'
        ACCEPTED = 'accepted', 'принято'
        REJECTED = 'rejected', 'отказано'
        CANCELED = 'canceled', 'отменено'

    initiator = models.ForeignKey('players.Player', on_delete=models.CASCADE, related_name='invitation_initiator',
                                  verbose_name='Инициатор')
    invited = models.ForeignKey('players.Player', on_delete=models.CASCADE, verbose_name='Приглашенный')
    invitation = models.BooleanField(default=True, verbose_name='Поле для работы уведомлений приглашений')
    status = models.CharField(max_length=20, choices=STATUS.choices, default=STATUS.ACTIVE,
                              verbose_name="Статус приглашения")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания записи')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения записи')

    class Meta:
        verbose_name_plural = 'Приглашения'
        verbose_name = 'Приглашение'

    def __str__(self):
        return f'Приглашение #{self.pk}'

events/forms.py
from django import forms
from django.core.validators import MinValueValidator
from datetime import datetime
from django.utils import timezone
from django.utils.timezone import make_aware

from clubs.models import Club
from .models import Event
from additions.models import City


class EventCreationForm(forms.ModelForm):
    name = forms.CharField(label='Название события', widget=forms.TextInput(attrs={'class': 'm-1'}))
    is_open = forms.ChoiceField(label='Открытый/закрытый', choices=Event.OPEN.choices,
                                widget=forms.Select(attrs={'class': 'm-1'}))
    city = forms.ModelChoiceField(label='Город', queryset=City.objects.all(),
                                  widget=forms.Select(attrs={'class': 'm-1'}))
    club = forms.ModelChoiceField(queryset=None, label='Клуб', required=False,
                                  widget=forms.Select(attrs={'class': 'm-1'}))
    start_date = forms.DateField(label='Дата начала встречи', widget=forms.SelectDateWidget(attrs={'class': 'm-1'}))
    start_time = forms.TimeField(label='Время начала встречи', widget=forms.Select(
        choices=[(datetime.strptime(str(i), '%H').time(), datetime.strptime(str(i), '%H').
                  strftime('%H:%M')) for i in range(24)], attrs={'class': 'm-1'}))
    finish_date = forms.DateField(label='Дата завершения встречи', widget=forms.SelectDateWidget(attrs={'class': 'm-1'}))
    finish_time = forms.TimeField(label='Время завершения встречи', widget=forms.Select(
        choices=[(datetime.strptime(str(i), '%H').time(), datetime.strptime(str(i), '%H').
                  strftime('%H:%M')) for i in range(24)], attrs={'class': 'm-1'}))
    addr = forms.CharField(label='Адрес', required=False, widget=forms.TextInput(attrs={'class': 'm-1'}))
    description = forms.CharField(label='Описание', required=False, widget=forms.Textarea(attrs={'class': 'm-1'}))

    # def clean(self):
    #     cleaned_data = super().clean()
    #     start_date = cleaned_data.get("start_date")
    #     start_time = cleaned_data.get("start_time")
    #     finish_date = cleaned_data.get("finish_date")
    #     finish_time = cleaned_data.get("finish_time")
    #
    #     if start_date and start_time and finish_date and finish_time:
    #         start_datetime = datetime.combine(start_date, start_time)
    #         finish_datetime = datetime.combine(finish_date, finish_time)
    #
    #         if start_datetime >= finish_datetime:
    #             raise forms.ValidationError("Дата и время завершения должны быть позже даты и времени начала.")
    #
    #         if start_datetime <= make_aware(datetime.now(), timezone.utc):
    #             raise forms.ValidationError("Дата и время начала должны быть позже текущей даты и времени.")
    #
    #     return cleaned_data
    def __init__(self, *args, **kwargs):
        request = kwargs.pop('request', None)
        super(EventCreationForm, self).__init__(*args, **kwargs)

        if request:
            # Получаем текущего пользователя из запроса
            user = request.user

            # Получаем клубы, в которых пользователь является членом
            clubs = Club.objects.filter(members__in=[user])

            # Отфильтровать клубы, доступные текущему пользователю
            self.fields['club'].queryset = clubs

            # Добавить пустое значение в список клубов
            choices = list(self.fields['club'].choices)
            self.fields['club'].choices = choices

    class Meta:
        model = Event
        fields = ['name', 'is_open', 'start_time', 'start_date', 'finish_time', 'finish_date',
                  'city', 'club', 'addr', 'description']

templates/events/ajax_invitation_one_player.html
{% load static %}
<script src="{% static 'js/jquery-3.7.1.min.js' %}"></script>
<script>
$(document).ready(function(){
    $('.invite-player').click(function(e){
        e.preventDefault();
        var button = $(this);
        var player_pk = button.data('player-pk');
        var container = button.closest('.card-body');

        // Проверяем, был ли уже отправлен запрос для данного игрока
        if (container.data('request-sent')) {
            return; // Если запрос уже был отправлен, выходим из функции
        }

        // Устанавливаем флаг, что запрос отправлен
        container.data('request-sent', true);

        $.ajax({
            url: button.attr('href'),
            type: 'POST',
            data: { 'csrfmiddlewaretoken': '{{ csrf_token }}' },
            success: function(response){
                if (response.success) {
                    container.find('.invite-status').html('Приглашение отправлено');
                    button.remove();
                } else {
                    var message = 'Сегодня этого игрока Вы уже пригласили. Ожидайте его ответа.';
                    container.find('.invite-status').html('<span class="text-danger">' + message + '</span>');
                    button.remove();
                }
            },
            error: function(xhr, status, error) {
                console.error("AJAX error occurred:", xhr.responseText);
            }
        });
    });
});
</script>

templates/events/create_event.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ title }}{% endblock %}
{% block content %}

<h2>{{ title }}</h2>
<div class="mb-4 col-12 col-md-6 col-lg-4">
    {% if update %}
        <form method="POST" action="{% url 'events:update_event' event.pk %}" enctype="multipart/form-data">
    {% else %}
        <form method="POST" action="{% url 'events:create_event' %}" enctype="multipart/form-data">
    {% endif %}
       {% csrf_token %}
       <table class="registration-form">
        <tr>
            <td>
                <label for="{{ form.name.id_for_label }}">Название события</label>
            </td>
            <td valign="top">
                {{ form.name }}
            </td>
        </tr>

        <tr>
            <td>
                <label for="{{ form.is_open.id_for_label }}">Открытое/закрытое</label>
            </td>
            <td valign="top">
                {{ form.is_open }}
            </td>
        </tr>

        <tr>
            <td>
                <label for="{{ form.city.id_for_label }}">Город</label>
            </td>
            <td valign="top">
                {{ form.city }}
            </td>
        </tr>

        <tr>
            <td>
                <label for="{{ form.start_time.id_for_label }}">Начало</label>
            </td>
            <td>
                {{ form.start_time }}{{ form.start_date }}
            </td>
        </tr>

        <tr>
            <td>
                <label for="{{ form.finish_time.id_for_label }}">Завершение</label>
            </td>
            <td>
                {{ form.finish_time }}{{ form.finish_date }}
            </td>
        </tr>

        <tr>
            <td>
                <label for="{{ form.addr.id_for_label }}">Адрес</label>
            </td>
            <td valign="top">
                {{ form.addr }}
            </td>
        </tr>

        <tr>
            <td>
                <label for="{{ form.description.id_for_label }}">Описание</label>
            </td>
            <td valign="top">
                {{ form.description }}
            </td>
        </tr>
    </table>

        <div class="my-2" style="background-color: rgba(255, 0, 0, 0.1);">
            {{ form.name.errors }}
            {{ form.is_open.errors }}
            {{ form.city.errors }}
            {{ form.club.errors }}
            {{ form.start_time.errors }}
            {{ form.start_date.errors }}
            {{ form.finish_time.errors }}
            {{ form.finish_date.errors }}
            {{ form.addr.errors }}
            {{ form.description.errors }}
        </div>
        {% if update %}
            <button type="submit" class="btn btn-primary text-uppercase">Редактировать</button>
        {% else %}
            <button type="submit" class="btn btn-primary text-uppercase">Добавить событие</button>
        {% endif %}
    </form>
</div>


{% endblock content %}

templates/events/edit_event.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ title }}{% endblock %}
{% block content %}

<h2>{{ title }}</h2>
<div class="mb-4 col-12 col-md-6 col-lg-4">
    <form method="POST" action="{% url 'events:creating_news' %}" enctype="multipart/form-data">
       {% csrf_token %}
       <table class="registration-form">
        <tr>
            <td>
                <label for="{{ form.name.id_for_label }}">Заголовок</label>
            </td>
            <td valign="top">
                {{ form.name }}
            </td>
        </tr>

        <tr>
            <td>
                <label for="{{ form.club.id_for_label }}">Клуб</label>
            </td>
            <td valign="top">
                {{ form.club }}
            </td>
        </tr>

        <tr>
            <td>
                <label for="{{ form.keywords.id_for_label }}">Ключевые слова</label>
            </td>
            <td valign="top">
                {{ form.keywords }}
            </td>
        </tr>

        <tr>
            <td>
                <label for="{{ form.content.id_for_label }}">Контент</label>
            </td>
            <td valign="top">
                {{ form.content }}
            </td>
        </tr>

        <tr>
            <td>
                <label for="{{ form.cover.id_for_label }}">Обложка</label>
            </td>
            <td>
                {{ form.cover }}
            </td>
        </tr>

        <tr>
            <td>
                <label for="{{ form.is_open.id_for_label }}">Доступно всем</label>
            </td>
            <td valign="top">
                {{ form.is_open }}
            </td>
        </tr>
    </table>

        <div class="my-2" style="background-color: rgba(255, 0, 0, 0.1);">
            {{ form.name.errors }}
            {{ form.keywords.errors }}
            {{ form.content.errors }}
            {{ form.cover.errors }}
            {{ form.is_open.errors }}
            {{ form.club.errors }}
        </div>

        <button type="submit" class="btn btn-primary text-uppercase">Добавить новость</button>
    </form>
    <br>
    <p><i>Если Вы являетесь владельцем клуба, к которому относится новость, то она будет опубликована прямо сейчас.
        В противном случае материал попадёт на рассмотрении владельцу клуба/администратору сайта, которые примут
        решение о публикации.
    </i></p>
</div>


{% endblock content %}

templates/events/event.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Поиск спарринг-партнёров{% endblock %}
{% block content %}
<div class="container d-flex justify-content-center my-2">
    <div>
        {% if user.is_authenticated %}
            <h3>{{ event.name }}</h3>
            {% if user in event.participants.all or user in event.allowed_participants.all or event.is_open %}
                <strong>Инициатор:</strong> {{ event.initiator }}
                <br>
                <strong>Статус встречи:</strong> {{ event.get_status_display }}
                <br>
                <strong>Открытость/закрытость события:</strong> {{ event.get_is_open_display }}
                <br>
                <strong>Количество участников:</strong> {{ event.participants.all|length }}
                <br>
                <strong>Участники события:</strong>
                {% for participant in event.participants.all %}
                    <span><a href="{% url 'players:player_info' username=participant.username %}">{{ participant }} </a></span>
                {% endfor %}

                {% if event.start_time %}
                    <br>
                    <strong>Начало:</strong> {{ event.start_time }} {{ event.start_date }}
                {% else %}
                    <br>
                    <strong>Начало:</strong> инициатор пока не установил время
                {% endif %}

                {% if event.finish_time %}
                    <br>
                    <strong>Завершение:</strong> {{ event.finish_time }} {{ event.finish_date }}
                {% else %}
                    <br>
                    <strong>Завершение:</strong> инициатор пока не установил время
                {% endif %}

                {% if event.city %}
                    <br>
                    <strong>Город:</strong> {{ event.city }}
                {% else %}
                    <br>
                    <strong>Город:</strong> инициатор пока не добавил город
                {% endif %}

                {% if event.addr %}
                    <br>
                    <strong>Адрес:</strong> {{ event.addr }}
                {% else %}
                    <br>
                    <strong>Адрес:</strong> инициатор пока не добавил информацию по этому пункту
                {% endif %}

                {% if event.description %}
                    <br>
                    <strong>Описание:</strong> {{ event.description }}
                {% else %}
                    <br>
                    <strong>Описание:</strong> инициатор пока не добавил описание встречи
                {% endif %}

                {% if request.user == event.initiator %}
                    <br>
                    <a href="{% url 'events:update_event' pk=event.pk %}" class="btn btn-secondary">Изменить</a>
                {% elif event.is_open and request.user not in event.participants.all %}
                    <br>
                    <a href="{% url 'events:join_the_club' event_pk=event.pk %}" class="btn btn-primary">Участвовать</a>
                {% endif %}

                <h4 class="mt-2">Комментарии</h4>
                <form method="post">
                    {% csrf_token %}
                    <textarea name="comment" rows="4" cols="50"></textarea><br>
                    <input type="submit" class="btn btn-primary" value="Добавить комментарий">
                </form>

                <ul class="list-group mt-3">
                    {% for comment in event.comments.all %}
                    <li class="list-group-item">{{ comment.text }}</li>
                    {% endfor %}
                </ul>
            {% else %}
                <p>Эта приватная встреча. Только инициатор может выслать Вам приглашение.</p>
            {% endif %}
        {% else %}
            <p>Чтобы увидеть информацию о встрече, войдите в свой аккаунт.</p>
        {% endif %}
    </div>
</div>

{% endblock content %}

templates/events/event_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ title }}{% endblock %}
{% block javascripts %}{% include 'news/news_like.html' %}{% endblock %}

{% block content %}
<div class="container mt-3">
  <h3 class="text-center">{{ title }}</h3>
  {% for item in events %}
    <div class="card mb-4">
      <div class="card-body">
        <h5 class="card-title">{{ item.name }}</h5>
          <small class="text-muted">Начало: {{ item.start_time }} {{ item.start_date }}</small>
          <br>
          <small class="text-muted">Завершение: {{ item.finish_time }} {{ item.finish_date }}</small>
        <br>
          <small class="text-muted">Инициатор: <a href="{% url 'players:player_info' username=item.initiator.username %}">{{ item.initiator.username }}</a></small>
        <br>
        <small class="text-muted">Участников: {{ item.participants.all|length }}</small>
        <br>
          {% if item.club %}
            {% if item.club.is_open or request.user in item.club.members.all %}
              <small class="text-muted">Событие связано с клубом "<a href="{% url 'clubs:club' item.club.pk %}">{{ item.club.name }}"</a></small>
            {% else %}
              <small class="text-muted">Событие связано с клубом "{{ item.club.name }}"</small>
            {% endif %}
            <br>
          {% endif %}
        <small class="text-muted">Город: {{ item.city.name }}</small>
        <br>
          <small class="text-muted">Адрес: {{ item.addr }}</small>
        <br>
        <a href="{% url 'events:event' event_pk=item.pk %}" class="btn btn-primary">Подробнее</a>
      </div>
    </div>
  {% endfor %}
  {% include 'paginator.html' %}
</div>

{% endblock %}

templates/events/search_partner.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Поиск спарринг-партнёров{% endblock %}
{% block content %}
<!-- Форма для поиска партнёра -->
{% include 'players/players_filter.html' %}

    <!-- Список подходящих игроков -->
    <div class="mb-4 col-12 col-md-6 col-lg-8">
        {% if players_count %}
            <h4>Подходящие игроки: {{ players_count }}</h4>
        {% else %}
            <h4>Подходящий игроков нет или Вы уже всех пригласили</h4>
            <p>Каждого игрока можно пригласить на одиночную встречу только один раз за день.</p>
        {% endif %}
        <!-- Карточка игрока -->
        {% for player in page_obj %}
            {% if player.searchable %}
                <div class="card mb-3">
                    <div class="card-body">
                        <h5 class="card-title"><a href="{% url 'players:player_info' username=player.username %}">{{ player.username }}</a></h5>
                        {% if player.first_name %}
                            <h5 class="card-title">{{ player.first_name }}
                                {% if player.last_name %}
                                    {{ player.last_name }}
                                {% endif %}
                            </h5>
                        {% endif %}
                        <p class="card-text"><strong>Рейтинг:</strong> {{ player.latest_rating }}</p>
                        {% if player.sex %}
                            <p class="card-text"><strong>Пол:</strong> {{ player.get_sex_display }}</p>
                        {% endif %}
                        {% if player.age %}
                            <p class="card-text"><strong>Возраст:</strong> {{ player.age }}</p>
                        {% endif %}
                        {% if player.role %}
                            <p class="card-text"><strong>Роль:</strong> {{ player.get_role_display }}</p>
                        {% endif %}
                        {% if player.skill_level %}
                            <p class="card-text"><strong>Уровень игры:</strong> {{ player.get_skill_level_display }}</p>
                        {% endif %}
                        {% if player.playstyle %}
                            <p class="card-text"><strong>Стиль игры:</strong> {{ player.get_playstyle_display }}</p>
                        {% endif %}
                        {% if player.hand %}
                            <p class="card-text"><strong>Игровая рука:</strong> {{ player.get_hand_display }}</p>
                        {% endif %}
                        {% if player.city %}
                            <p class="card-text"><strong>Город:</strong> {{ player.city.name }}</p>
                        {% endif %}
                        {% include 'events/ajax_invitation_one_player.html' %}
                        <p class="invite-status"><i id="will-change-{{ player.pk }}"></i></p> <!-- Изменил идентификатор на класс -->
                        <a href="{% url 'events:invite_to_play' player_pk=player.pk %}" class="btn btn-primary invite-player text-uppercase m-1" data-player-pk="{{ player.pk }}">Пригласить поиграть</a>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
        {% include 'paginator_with_filter.html' %}
    </div>

{% endblock content %}